### ISSUE TITLE
[Bug] Minesweeper - Automatically unveiling fields via left +right click according to flags doesn't win the game

### ISSUE THREAD

**Issue by arthemis95** [greflm13/Homepage#2]
As the title says. When marking the remaining mines with flags, and auto unveiling fields with left + right click the game logic doesn't properly win the game. Instead you have to left click on the game field again, in order for it to register.

This has ruined a couple of my record times, because I had to double check that I haven't accidentally flagged too many mines.

Literally unplayable

Volvo please fix

and so on and so forth

**Comment by greflm13** [comment]
should be fixed
