### ISSUE TITLE
[Improvement] Minesweeper - Bomb placement algorithm 

### ISSUE THREAD

**Issue by arthemis95** [greflm13/Homepage#3]
Hello dear maintainer. 

I've been enjoying minesweeping quite a lot. However it is rather annoying that unveiling the first mine yields a field that already is adjacent to mines. I think changing the algorithm that avoids unveiling a mine as your first move to also reroll the seed, if you unveil a field adjacent to a mine. 

This would greatly improve the speed at which one can start over.

With best regards

**Comment by greflm13** [comment]
fixed, now i have a challenge, play 9x9 with max bombs
